template: external-bridged-provider
provider: grafana
organization: pulumiverse
major-version: 0
providerDefaultBranch: main
upstreamProviderOrg: grafana
publishRegistry: false
enableAutoRelease: false
plugins:
  - name: terraform
    version: "1.0.19"
    kind: converter
  - name: random
    version: "4.16.7"
  - name: aws
    version: "6.56.1"
languages:
  - dotnet
  - go
  - nodejs
  - python
publish:
  sdk: "all,!java"
  cdn: false
# license:
#   ignore:
pr-assign: ringods
toolVersions:
  go: "1.22.x"
pulumiConvert: 1
